### ISSUE TITLE
[建议]添加中等大小窗口
[Suggestion]Add Medium Window

### ISSUE THREAD

**Issue by daybreak1929** [WorldBoxOpenMods/ModLoader#18]
目前大窗口有点太宽了，应该加一个两倍宽度(相比原版)的窗口，效果如图
![IMG_20240429_134131.png](https://github.com/WorldBoxOpenMods/ModLoader/assets/152311825/5f108b17-d020-4745-aa3e-7396d97248d4)

**Comment by inmny** [comment]
949d11841584ec92f5a5cb421ad8f31dd65a87ab 已实现相关功能
